### PR TITLE
fix: Take csrf token from CMS config if possible

### LINKED ISSUE #437: [BUG] StateIndicatorMixin raises CSRF error with CSRF_USE_SESSIONS = True
## Description

I have a standard Grouper/Content model setup (Not dissimilar to djangocms-blog) where the publish/unpublish actions added via the `StateIndicatorMixin` do not work as expected and throw a 403 - CSRF token from POST incorrect.

From my testing this only occurs when we set `CSRF_USE_SESSIONS = True` in `settings.py`. Setting this to `False` gets things working again. Most other settings are reasonable defaults.

EDIT:
After deploying this to our development server it didn't actually fix the issue but now does raise something slightly more useful. With the setting marked as `False` I get

`Uncaught TypeError: document.cookie.match(...) is null` from https://github.com/django-cms/djangocms-versioning/blob/master/djangocms_versioning/static/djangocms_versioning/js/indicators.js#L12

Going back to a localhost instance with the setting as `True`
`Uncaught TypeError: window.top.CMS is undefined` from https://github.com/django-cms/djangocms-versioning/blob/master/djangocms_versioning/static/djangocms_versioning/js/indicators.js#L76

Some other things:
- This doesn't occur for Pages, only custom models which use the Grouper admin mixins.
- By going to "manage versions" instead you can publish or unpublish as expected.

## Steps to reproduce
1. Go to a custom grouper admin. e.g /admin/news/article/
2. Click on state indicator and select publish or unpublish
3. If not in sidebar, nothing happens, otherwise it will show the 403 in a modal.

## Expected behaviour

Page reloads and the object is marked as published/unpublished

## Actual behaviour

403 CSRF error is raised.

## Additional information (CMS/Python/Django versions)

CMS v4.1.1
Django 5.1.3
Djangocms-Versioning 2.1.0

## Snippet
```
@admin.register(Article)
class ArticleAdmin(StateIndicatorMixin, ExtendedGrouperVersionAdminMixin, GrouperModelAdmin):
    content_models = ArticleContent
    extra_grouping_fields = ("language",)
    list_display = ["title", "author", "state_indicator"]
    list_filter = ["author"]
    search_fields = ["author__name"]
    autocomplete_fields = ["author"]
    fieldsets = [...]


@admin.register(ArticleContent)
class ArticleContentAdmin(ExtendedIndicatorVersionAdminMixin, admin.ModelAdmin):
    fieldsets = [(None, {"fields": ["title", "intro", "slug"]}), admin_mixins.META_FIELDSET]

    def get_model_perms(self, request):
        """
        Return empty perms dict to hide the model from admin index.
        """
        return {}
```

## Do you want to help fix this issue?

* [ ] Yes, I want to help fix this issue and I will join the channel #pr-reviews on [the Discord Server](https://discord-pr-review-channel.django-cms.org) to confirm with the community that a PR is welcome.
* [x] No, I only want to report the issue.

### PR DESCRIPTION
**Pull request by fsbraun**
## Description

Bug Fixes:
- Fixed an issue where the CSRF token was not being fetched correctly.

Fixes #437 

## Related resources

* #437 
* #...

## Checklist

* [ ] I have opened this pull request against ``master``
* [ ] I have added or modified the tests when changing logic
* [ ] I have followed [the conventional commits guidelines](https://www.conventionalcommits.org/) to add meaningful information into the changelog
* [ ] I have read the [contribution guidelines ](https://github.com/django-cms/django-cms/blob/develop/CONTRIBUTING.rst) and I have joined #workgroup-pr-review on 
[Slack](https://www.django-cms.org/slack) to find a “pr review buddy” who is going to review my pull request.

### CODE REVIEW

**Comment by fsbraun** [comment]
@Will-Hoey Could you check if this PR solves your issue?

File: djangocms_versioning/static/djangocms_versioning/js/indicators.js [hunk 1]
```diff
@@ -5,19 +5,28 @@
...
+        let csrfToken = '';
+
         if (element.closest('.cms-pagetree-dropdown-item-disabled').length) {
             return;
         }
-        let csrfToken = document.cookie.match(/csrftoken=([^;]*);?/)[1];
+        if (window.top.CMS.config.csrf) {
+            csrfToken = window.top.CMS.config.csrf;
+        } else {
+            const cookieToken = document.cookie.match(/csrftoken=([^;]*);?/)
```
Comment (fsbraun) [inline djangocms_versioning/static/djangocms_versioning/js/indicators.js:17]:
```suggestion
            const cookieToken = document.cookie.match(/csrftoken=([^;]*);?/);
```

**Comment by fsbraun** [comment]
@will-hoey Can you quickly check if this patch solves your issue?

**Comment by Will-Hoey** [comment]
> @Will-Hoey Can you quickly check if this patch solves your issue?

Apologies for the delay. Busy week!

With `CSRF_USE_SESSIONS` as either value - when the admin is in the modal it works as expected, however the same issue occurs when not in the modal, at `admin/news/article/`.  The same console error of `window.top.CMS` is still there.

A side note, and this isn't really likely to be too much of a problem, if I switch that setting and then try any post request (logout, unpublish etc) it'll raise an incorrect token message unless I refresh the page. Kind of expected though!

**Comment by fsbraun** [comment]
@Will-Hoey Ah, right, that makes sense: In the admin (only) panel the CMS object is not available. In that case, the token needs to be pulled from a hidden input field. Do you think you can give it another try?

**Comment by Will-Hoey** [comment]
@fsbraun the new commit works when `CSRF_USE_SESSIONS = False` but not when it's `True`. Same js error as mentioned before

**Comment by fsbraun** [comment]
@Will-Hoey It works for me now. Maybe an outdated token still in the cookies? I've changed the order, so that the token from the form precedes the one in the cookies.

**Comment by fsbraun** [comment]
Thank you so much for the support! Sometimes the small things are more tricky than you expect!
